pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3'
        jdk 'jdk8'
    }
    stages {

        stage('Checkout ') {
            steps {
                git branch: 'master',
                url: 'https://github.com/paulagajewska/JDND.git/'

                sh "ls -lat"
            }
        }
        stage ('Build') {
            steps {
                sh './mvnw -f "projects/P04-eCommerce Application/starter_code/pom.xml" clean compile'
            }
        }
        stage ('Unit Test') {
            steps {
                sh './mvnw -f "projects/P04-eCommerce Application/starter_code/pom.xml" test'
            }
        }
        stage ('Integration Test') {
             steps {
                  sh './mvnw -f "projects/P04-eCommerce Application/starter_code/pom.xml" verify -Psurefile'
             }
       }
    }
}